@startuml POST
actor Actor as a
control Slim as s
control UserConstroller as uc
database MySQL as db
control MailerController as mc

a -> s : /change_password (token, password, password_confirm)
activate s
s -> uc : change_password(token, password, password_confirm)
activate uc

uc -> db :select (token mail datetime) from LostPassword where token
activate db
db --> uc :?(token mail datetime)
deactivate db
alt #bbff99 (token mail datetime)

alt #ccffaa (datetime - now) < 1h00
uc -> db :select * from Users where mail
activate db
db --> uc :user
deactivate db
else #ffaaaa (datetime - now) >= 1h00
uc -> db :delete from LostPassword where (token mail datetime)
activate db
uc <-- db
deactivate db
s <-- uc :"Invalid Token"
end

alt #ccffaa si password okay
uc -> db :update password
activate db
uc <-- db
deactivate db
uc -> db :delete from LostPassword where (token mail datetime)
activate db
uc <-- db
deactivate db
uc -> mc :Send_password_sucess(mail)
activate mc
note right
Envoie du mail
de confirmation
end note
uc <-- mc
deactivate mc
s <-- uc :"Password updated successfully"
deactivate mc

else #ffaaaa password pas okay
uc --> s :"Please type identical password!" || "Password invalid"
end

else #ff9999 !(token mail datetime)
uc --> s :"Invalid Token"
deactivate uc
end
deactivate uc
s --> a :change_password.html.twig
deactivate s

@enduml