@startuml POST
actor Actor as a
control Slim as s
control RequestController as rc
entity ElasticSearch as es

a -> s :/get_poi_type_data (json)
activate s
alt #88ff88 admin
s -> rc :Request_poi_with_sort(json)
activate rc

rc -> es :curl
rc <-- es :(data)

rc -> rc :création d'un tableau avec les infos des data de ES
activate rc

rc --> s :(json)
deactivate rc
deactivate rc
s --> a :(json)
deactivate s


@enduml