@startuml POST
actor Actor as a
control Slim as s
control UserConstroller as uc

a -> s : /resetpassword
activate s
s -> uc : recover_send_mail(mail)
activate uc
uc -> db :select mail where mail
activate db
db --> uc :?mail
deactivate db
alt  #5df33f mail
uc -> db :select token, mail, datetime where mail (table LostPassword)
activate db
db --> uc :?(token, mail, datetime)
deactivate db

alt  #ccffaa (token, mail, datetime)
uc -> uc :génère token
activate uc
uc -> db :update LostPassword token where mail
activate db
db --> uc
deactivate db
uc -> mc : Send_Reset_Mail(mail, token)
activate mc
mc --> uc :true | false
deactivate mc
deactivate uc

uc --> s :"Please check your email and click on the link to reset your password"


else #FFAAAA !(token, mail, datetime)
uc -> db :insert into LostPassword
activate db
db -->uc
deactivate db
end

else  #f33f3f !mail
uc --> s :"Mail not found in our database"
end

uc --> s
deactivate uc
s -> s :session_destroy()
s --> a :recover.html.twig
deactivate s

@enduml